
export const SELECCIONAR_CLIENTE = 'SELECIONAR_CLIENTE'
export const CANTIDAD_PRODUCTOS = 'CANTIDAD_PRODUCTOS'
export const SELECCIONAR_PRODUCTO = 'SELECIONAR_PRODUCTO'
export const ACTUALIZAR_TOTAL = 'ACTUALIZAR_TOTAL'
